language: java
script: mvn install
deploy:
  provider: heroku
  app : trilogyvz
  api_key:
    secure: "IDzMypynPJmi+vc5PlXa6Bl2j1bIPwK/SaS0NSkAEuHihafivBnQhF3ZlzfF6Xmer4/AYKxpU6wqpfjruRn/QS2i9WWyobp28CbTtfZGlNucYSx810pQbIxg1pnLOcI4fk/cmcsVWprAuE+D8NCxbkxS65gTiTfgDroLk9YV3WmSMpvu+8ebLroKkUQms5o35Bm4Gwnk0+qEf7+UWTTpllSzPfwR1sawR1aBNq7yAAB5haV97aLXDhfdOJtAKvlJ1XIlsJuSs1yD0eIt5aL9g7EsZwVGfu7QzCJF2w144ItACLohy/q3lYgP5Ei1zOCn8qbYWU4O7w/goHmKJuA1Bsx+8eepnOD9mh8v/3NJmLLOFZJWqRbhPRM75lQbD7BP22eUUZHbA2XcrBk631XISZR7aNQfOMCVYABnb3vvilwcm9hi+co7YAWFq3cf/xCzYP94I4kPrX30qRzGN5Or9Q9vO5LqX9ikAWHp6ci4Cc6WfXeeh/gYyqFrQP1aB1BOjqWVuZepalL3fAO16D5KvDE2ipd2aOD8Z7IKVJnKaAfJ8iV8h4euAqaUn2Y8eI8lsOJXxef2CtjbdMPQy6QMk2RJ1iNpaW6I/76+b3iCiaU8DO/rz7uh/+S8CLmk1ZBRmq1XNzFNHKlraB5c8hBxXVMETpC78zyO7auZS1tgtL4="
